/**
 * SKUs API
 * A stock keeping unit (SKU) represents a specific product variation.   <a name=\"sku-object\"></a>     # The SKU object  The SKU object provides product information.  <table> <tr>     <td><b>Attributes</b></td>     <td><b>Description</b></td> </tr> <tr>     <td><b>createdTime</b>     <br>     datetime</td>     <td>The time when the SKU was created.</td> </tr>     <tr>     <td><b>id</b>     <br>     string</td>     <td>Unique identifier of a SKU.</td> </tr> <tr>     <td><b>eccn</b>     <br>     string</td>     <td>The Export Control Classification Number.</td> </tr>      <tr>     <td><b>taxCode</b>     <br>     string</td>     <td>The tax code.</td> </tr>    <tr>     <td><b>name</b>     <br>     string</td>     <td>The product\'s name.</td> </tr>    <tr>     <td><b>countryOfOrigin</b>     string<br>     </td>     <td>Two-letter country code.</td> </tr> <tr>     <td><b>weight</b>     <br>     number</td>     <td>The weight of the SKU in the unit system specified with weightUnit</td> </tr>    <tr>     <td><b>weightUnit</b>     <br>     string</td>     <td>The unit of measurement that applies to the SKU weight. If you do not specify a value for weightUnit, then the default unit of measurement is applied.</td> </tr>   <tr>     <td><b>liveMode</b>     <br>     boolean</td>     <td>Has the value is true of the object exists in live mode or the value false if the object exists in test mode.</td> </tr>   </table>  ## SKU object example     {       \"createdTime\": \"2018-04-25T20:36:00Z\",       \"id\": \"sku_5823594809\",       \"eccn\": \"EAR99\",       \"taxCode\": \"4323.310_A\",       \"name\": \"Athena Womens Running Shoes\",       \"countryOfOrigin\": \"US\",       \"weight\": 20.5,       \"weightUnit\": \"oz\",       \"liveMode\": false     }
 *
 * The version of the OpenAPI document: 1.0.14
 * Contact: aknights@digitalriver.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export declare class Sku {
    /**
    * Time when the SKU was created.
    */
    'createdTime'?: Date;
    /**
    * Unique identifier of a SKU.
    */
    'id'?: string;
    /**
    * Export control classification number.
    */
    'eccn'?: string;
    /**
    * Has the value true if the SKU is physical. Default is false.
    */
    'physical'?: boolean;
    /**
    * Sabrix tax code.
    */
    'taxCode'?: string;
    /**
    * The product’s name.
    */
    'name'?: string;
    /**
    * A description of the product.
    */
    'description'?: string;
    /**
    * An image of the product.
    */
    'image'?: string;
    /**
    * A product url.
    */
    'url'?: string;
    /**
    * 2-letter country code.
    */
    'countryOfOrigin'?: string;
    /**
    * The weight of the sku in the unit system specified with weightUnit.
    */
    'weight'?: number;
    /**
    * The unit of measurement that applies to the sku weight. If you do not specify a value for weightUnit, then the default unit of measurement is applied.
    */
    'weightUnit'?: Sku.WeightUnitEnum;
    /**
    * Has the value true if the object exists in live mode or the value false if the object exists in test mode.
    */
    'liveMode'?: boolean;
    'metadata'?: any;
    /**
    * Time when the SKU was last updated.
    */
    'updatedTime'?: Date;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
export declare namespace Sku {
    enum WeightUnitEnum {
        Oz,
        Lb,
        G,
        Kg
    }
}
